import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import PageTransition from "./components/PageTransition";

const Josefins = Josefin_Sans({
  subsets: ["Latin"],
  weight: ["200", "400", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Josefins.className} max-w-[1380px] mx-auto`}>
        <NavBar />
        <PageTransition>{children}</PageTransition>

        <Footer />
      </body>
    </html>
  );
}
